baseURL = "https://lambheart.github.io/"
title = "Celeste Li"
languageCode = "en-us"

[params]
    author = "Celeste Li"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true